version: '3.7'

x-variables: &x-variables
  APP_ENV: dev
  APP_SECRET: c95ab68cbfba3232e79d72ebae567424
  MINIO_ENDPOINT: http://minio:9000
  MINIO_ACCESS_KEY: medley
  MINIO_BUCKET: medley
  MINIO_SECRET_KEY: h15QXfIaJVdcTQdqTQm6pYwYjFa7x87TfhF47CPf

services:
  nginx:
    image: medley/nginx
    build:
     context: ./
     dockerfile: Dockerfile-nginx
    environment: *x-variables
    ports:
     - "8000:443"
    depends_on:
     - fpm
  fpm:
    image: medley/selfhosted-agent
    build:
      context: ./
      dockerfile: Dockerfile
    environment: *x-variables
    # volumes:
    #  - ./bin:/var/www/bin
    #  - ./src:/var/www/src
    #  - ./templates:/var/www/templates
    #  - ./vendor:/var/www/vendor

  minio:
    image: minio/minio
    hostname: minio
    environment: *x-variables
    volumes:
     - minio-data:/data
    ports:
     - "8001:9000"
    command: server /data

volumes:
  minio-data: